/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programaritmatika;

/**
 *
 * @author Savina
 */
public class Frame1 extends javax.swing.JFrame {

    String jns="";
    int jml;
    
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        getJumlah();
        setJenis();
        panel.setVisible(false);
        pilihanbil.setEnabled(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        panel = new javax.swing.JPanel();
        keterangan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        pilihanbil = new javax.swing.JComboBox<>();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        bil3 = new javax.swing.JTextField();
        bil4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        thasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel1.setText("Program Aritmatika");

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        jLabel2.setText("Jenis Operasi Aritmatika");

        jenis.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Operasi -", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Operasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Banner", 0, 14))); // NOI18N

        keterangan.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        keterangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keterangan.setAlignmentX(5.0F);
        keterangan.setAlignmentY(10.0F);

        jLabel4.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        jLabel4.setText("Jumlah Bilangan");

        b1.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        b1.setText("Bilangan 1");

        b2.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        b2.setText("Bilangan 2");

        b3.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        b3.setText("Bilangan 3");

        b4.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        b4.setText("Bilangan 4");

        pilihanbil.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });

        bil1.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N

        bil2.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N

        bil3.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N

        bil4.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N
        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        thasil.setFont(new java.awt.Font("Sitka Banner", 0, 14)); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thasil, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(b1)
                            .addComponent(b2)
                            .addComponent(b3)
                            .addComponent(b4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bil1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pilihanbil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bil2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bil3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bil4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pilihanbil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(bil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2)
                    .addComponent(bil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3)
                    .addComponent(bil3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4)
                    .addComponent(bil4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thasil, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double hsl = 0.0;
        Double a1,a2,a3,a4;
        a1 = Double.parseDouble(bil1.getText().toString());
        a2 = Double.parseDouble(bil2.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml == 2) {
                hsl = a1 + a2;
                thasil.setText(""+a1 + " + " +a2 + " = "+ hsl);
            }
            
            if(jml == 3) {
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 + a2 + a3;
                thasil.setText(""+a1 + " + " +a2 + " + "+ a3 + " = " + hsl);
            }
            
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                thasil.setText(""+a1 + " + " +a2 + " + "+ a3 + " + " + a4 + " = " + hsl);
            }
        }
        
        else if(jns.equals("Pengurangan")) {
            if(jml == 2) {
                hsl = a1 - a2;
                thasil.setText(""+a1 + " - " +a2 + " = "+ hsl);
            }
            
            if(jml == 3) {
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 - a2 - a3;
                thasil.setText(""+a1 + " - " +a2 + " - "+ a3 + " = " + hsl);
            }
            
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                thasil.setText(""+a1 + " - " +a2 + " - "+ a3 + " - " + a4 + " = " + hsl);
            }
        }
        
        else if(jns.equals("Perkalian")) {
            if(jml == 2) {
                hsl = a1 * a2;
                thasil.setText(""+a1 + " * " +a2 + " = "+ hsl);
            }
            
            if(jml == 3) {
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 * a2 * a3;
                thasil.setText(""+a1 + " * " +a2 + " * "+ a3 + " = " + hsl);
            }
            
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                thasil.setText(""+a1 + " * " +a2 + " * "+ a3 + " * " + a4 + " = " + hsl);
            }
        }
        
        else if(jns.equals("Pembagian")) {
            if(jml == 2) {
                hsl = a1 / a2;
                thasil.setText(""+a1 + " / " +a2 + " = "+ hsl);
            }
            
            if(jml == 3) {
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 / a2 / a3;
                thasil.setText(""+a1 + " / " +a2 + " / "+ a3 + " = " + hsl);
            }
            
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                thasil.setText(""+a1 + " / " +a2 + " / "+ a3 + " / " + a4 + " = " + hsl);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setJenis()
    {
        if(jenis.getSelectedItem().equals("Penjumlahan")) {
            jns = "Penjumlahan";
            keterangan.setText("Penjumlahan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
            
        }
        
        else if(jenis.getSelectedItem().equals("Pengurangan")) {
            jns = "Pengurangan";
            keterangan.setText("Pengurangan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        
        else if(jenis.getSelectedItem().equals("Perkalian")) {
            jns = "Perkalian";
            keterangan.setText("Perkalian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        
        else if(jenis.getSelectedItem().equals("Pembagian")) {
            jns = "Pembagian";
            keterangan.setText("Pembagian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
    }
    
    public void getJumlah()
    {
        if(pilihanbil.getSelectedItem().equals("2")) {
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        b1.setVisible(true);
        b2.setVisible(true);
        bil1.setVisible(true);
        bil2.setVisible(true);
        jml = 2;
        }
        
        else if(pilihanbil.getSelectedItem().equals("3")) {
        bil3.setVisible(true);
        bil4.setVisible(false);
        b3.setVisible(true);
        b4.setVisible(false);
        jml = 3;
        }
        
        else if(pilihanbil.getSelectedItem().equals("4")) {
        bil3.setVisible(true);
        bil4.setVisible(true);
        b3.setVisible(true);
        b4.setVisible(true);
        jml = 4;
        }
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel keterangan;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilihanbil;
    private javax.swing.JTextField thasil;
    // End of variables declaration//GEN-END:variables
}
